version: '3.8'

services:
  # Fast Blockchain Indexer (Runs Continuously)
  indexer:
    build: .
    container_name: lucky_ponds_indexer
    command: python indexer.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - lucky_ponds_network

  # Enhanced Scheduler (Points Calculator + Winner Selection + Health Checks)
  scheduler:
    build: .
    container_name: lucky_ponds_scheduler
    command: python scheduler.py --points-interval ${POINTS_CALCULATION_INTERVAL:-3600} --winner-interval ${WINNER_SELECTION_INTERVAL:-300}
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - lucky_ponds_network
    depends_on:
      - indexer

  # API Server
  api:
    build: .
    container_name: lucky_ponds_api
    command: gunicorn --bind 0.0.0.0:5000 app:app --workers 4 --timeout 120
    ports:
      - "${API_PORT:-5000}:5000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - lucky_ponds_network
    depends_on:
      - indexer
      - scheduler

  # One-time Database Setup
  setup:
    build: .
    container_name: lucky_ponds_setup
    command: python db_setup.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - lucky_ponds_network

networks:
  lucky_ponds_network:
    driver: bridge